// Generated by unrouted
declare module '@unrouted/core' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface _871028989 {
     id: number,

    title: string,

    postedAt: string,

    description: string,
  }

  interface GetRoutes {
    '/__api/dynamic-type-return': Awaited<_871028989>
  }
  interface HeadRoutes {
    '/__api/dynamic-type-return': Awaited<_871028989>
  }
}

export {}
