// Generated by unrouted
declare module '@unrouted/core' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface _1015972996 {
     id: number,

    title: string,

    postedAt: string,

    description: string,
  }

  interface GetRoutes {
    '/__api/dynamic-type-return': Awaited<_1015972996>
  }
}

export {}
